# Theme and plugins
# (Edit Dockerfile to install any necessary gems.)
safe: false
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Site metadata
author: GitHub User
description: Write an awesome description for your new site here.
title: Your awesome title

# Contact info
email: your-email@domain.com
github_username: jekyll
twitter_username: jekyllrb

# Content filters
future: false
show_drafts: null
unpublished: false

# Markdown -> HTML converter
highlighter: rouge
markdown: kramdown
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'
kramdown:
  input: GFM

# File and folder paths
source: .
destination: ./_site
exclude:
  - .gitignore
  - bin
  - Dockerfile
  - LICENCE
  - README.md
